### PR TITLE
Fixes gh_25: adapted the code for latest foreman

### PR DESCRIPTION
**Pull request by ShimShtein**

### CODE REVIEW

**Comment by ohadlevy** [comment]
@ShimShtein any reason not to merge this in?

**Comment by ShimShtein** [comment]
As always - I'd prefer a second pair of eyes on the code before it's merged. It passes sanity on my machine and the plugin doesn't work at all without it, so I guess it can be merged and we deal with the aftermath later.

**Comment by ohadlevy** [comment]
:+1:

**Comment by tstrachota** [comment]
:+1: thanks, Shim!

**Pull request merged**
